### ISSUE TITLE
Remove link to Deleting-a-Node from wiki

### ISSUE THREAD

**Issue by phahulin** [poanetwork/wiki#31]
https://github.com/poanetwork/wiki/wiki/Deleting-a-Node is correct in itself, but is applicable to azure  templates that are not used now (ansible playbooks are used instead). In future we'll probably make azure templates up-to-date with playbooks, so I propose to not delete this file completely, but remove the reference to it from wiki.
Validator's AWS instructions mention how to remove an existing node from aws: https://github.com/poanetwork/wiki/blob/master/validator-guide-new.md#remove-instance

**Comment by hashguide** [comment]
All set, removed from Home.md and _Sidebar.md
