### ISSUE TITLE
Navigation structure for Wiki

### ISSUE THREAD

**Issue by igorbarinov** [poanetwork/wiki#34]
```
Getting started/
 Installation [TBD]
 Wallets/
   MEW
   Ledger
   Tresor
   Trust
 Exchanges [TBD]
 FAQ
Roles/
 Validator/
   AWS
   Non-AWS
 Master of Ceremony
 Full/Boot node operator/
    AWS
    Non-AWS
POA/
  Papers [TBD]
  What is POA
  Governance
  Role of validator [TBD]
```
For TBD section, please create placeholder pages

**Comment by hashguide** [comment]
Should "Full/Boot node operator/" be Bootnode?   
  People might confuse Full Node as something they can run without having the `NETSTATS_SECRET`, such as a Full Parity or Geth node that will be created in the "Installation" section or possible having the connection part as an additional page in the "Full/Boot node operator/" section.

**Comment by igorbarinov** [comment]
@hashguide we can rename Full/Boot node operator to `Fullnode`
and make a section with a difference between full and bootnode

**Comment by hashguide** [comment]
Sounds good

**Comment by hashguide** [comment]
This index structure is complete
