### ISSUE TITLE
Bootnode Setup Non AWS

### ISSUE THREAD

**Issue by johnnynuuma** [poanetwork/wiki#37]
At least one member of community is using AWS to host a bootnode.  Are these instruction sufficient?  If so then should clean up "non-aws" language, if should there be a separate Bootnode Setup AWS document?

**Comment by phahulin** [comment]
1. If they create an instance themselves - instruction is sufficient
2. playbook can create an aws instance for them and configure aws security group - in this case instruction is missing some steps - I'll make a separate instruction for this case

**Comment by phahulin** [comment]
@hashguide Hi, please take a look at this guide https://gist.github.com/phahulin/ffc11c3ddd0a70da3874707441c396c7
if it looks good, add it to wiki in https://github.com/poanetwork/wiki/wiki/Bootnode-Setup-AWS
Thanks!

**Comment by hashguide** [comment]
Looks great, Added!
