### ISSUE TITLE
Managing deployment ( ssh ) keys guideline strategy and documentation

### ISSUE THREAD

**Issue by johnnynuuma** [poanetwork/wiki#40]
This issue is motivated by a long debug session around the Sokol Hard Fork upgrade process.   

A user had installed a bootnode on Azure using the ansible deployment-playbook scripts but was unable to update his node using the following documents:

https://github.com/poanetwork/wiki/wiki/HFs-Sokol-2018-01-08

In my view there are several issues: 

Specification -- There is no general strategy around how deployment ssh keys should be managed given a user may have multiple nodes running both on the testnet and core ( production ) networks.   For example, if a user is running both a bootnode and Validator node on production should they deployments use same ssh keys?   Further, if someone is running (2) Validator nodes on production, what then?

Implementation of deployments -- Scripts need to implement above specification or explicitly state what assumptions are around ssh key/pairs for deployments 

For above see Issue:  ( https://github.com/poanetwork/poa-devops/issues/6 )

Documentation -- using above can call out all assumptions or provide clear guidance

**Comment by hashguide** [comment]
I added to non-aws guide about creating different SSH keys for each network and a parameter added to ansible command `--key-file` to specify which key to use during deployment
