### ISSUE TITLE
Link does not work in "Chapter VI - in which MoC changes links in Validator's README" Master of Ceremony

### ISSUE THREAD

**Issue by MarcelMWS** [poanetwork/wiki#52]
Link does not work in "Chapter VI - in which MoC changes links in Validator's README": https://github.com/poanetwork/wiki/blob/master/validator-guide-new.md#exchange-your-initial-keys-for-mining-payout-and-voting-keys

**Comment by vbaranov** [comment]
Link is fixed: https://github.com/poanetwork/wiki/wiki/Master-of-Ceremony-Setup/_compare/bc09723aa9fb4e63e7d04144334bebb036d1ea16...710709a7819d75872070168fe9910e8a920ff6d8
Thanks!
