### ISSUE TITLE
Replace sokol-explorer.poa.network with sokol.poaexplorer.com in README

### ISSUE THREAD

**Issue by varasev** [poanetwork/wiki#58]
A suggestion is to replace an old sokol-explorer.poa.network with sokol.poaexplorer.com in README.md.

**Comment by 6proof** [comment]
If there the new poaexplorer.com is stable this would be excellent.

**Comment by varasev** [comment]
The link to `sokol.poaexplorer.com` was added in https://github.com/poanetwork/wiki/commit/af335a7d5d057a7acd8800c7046d10c2d7007418 along with the link to `Blockscout` explorer.
