### ISSUE TITLE
How do we know MASTER_OF_CEREMONY address?

### ISSUE THREAD

**Issue by kouohhashi** [poanetwork/wiki#59]
This is not issue but more like question.

I got stacked at **_POA Network Consensus contract process._**
The document says "where MASTER_OF_CEREMONY is the public address of Master of Ceremony from the previous step...". but I have no idea which step ...

Is MASTER_OF_CEREMONY address same as owner address?

Thanks in advance.

**Comment by vbaranov** [comment]
@kouohhashi 

> Is MASTER_OF_CEREMONY address same as owner address?

It is the confusion with definitions. Yes, as a first step you generate private and public keys for Master of Ceremony. I changed "owner" to "MoC (Master of Ceremony)" in Chapter 1. Is it more clear now?

**Comment by kouohhashi** [comment]
Thanks. not it's clear!
