### ISSUE TITLE
Add CytoWise to Wallets section in Wiki

### ISSUE THREAD

**Issue by SiddigZeidan** [poanetwork/wiki#61]
Add CytoWise to list of wallets. Image file is below:

https://onedrive.live.com/?authkey=%21AF1zq9zCXjOXpfQ&id=5719CE4C3F099FAC%21115570&cid=5719CE4C3F099FAC

**Comment by 6proof** [comment]
Could you please provide  direct link showing that the CytoWise wallet has been added to the POA Network Wiki?  I am unable to find.  Thanks!

**Comment by igorbarinov** [comment]
@SiddigZeidan

**Comment by SiddigZeidan** [comment]
https://github.com/poanetwork/wiki/wiki/Wallets
https://github.com/poanetwork/wiki/wiki/POA-Network-on-Citowise
